### ISSUE TITLE
panicked at 'memory overflow'

### ISSUE THREAD

**Issue by charlesxsh** [boa-dev/boa#1401]
**Describe the bug**
thread 'main' panicked at 'memory overflow'

**To Reproduce**
Input: 
`4n**44444444444444434444444434644446444444444444n`

Code:
```rust
fn main(){
    // let data = input

    let mut context = Context::new();
    context.eval(data);

}
```

Output
```
thread 'main' panicked at 'memory overflow', /home/xsh/code/rust-compiler/src/libstd/macros.rs:13:23
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
             at /home/xsh/code/rust-compiler/src/libstd/panicking.rs:456
   7: num_bigint::biguint::power::<impl num_traits::pow::Pow<&num_bigint::biguint::BigUint> for num_bigint::biguint::BigUint>::pow
             at /home/xsh/code/rust-compiler/src/libstd/macros.rs:13
   8: num_bigint::biguint::power::<impl num_traits::pow::Pow<num_bigint::biguint::BigUint> for num_bigint::biguint::BigUint>::pow
             at /home/xsh/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.3.2/src/biguint/power.rs:35
   9: num_bigint::bigint::power::<impl num_traits::pow::Pow<num_bigint::biguint::BigUint> for num_bigint::bigint::BigInt>::pow
             at /home/xsh/.cargo/registry/src/github.com-1ecc6299db9ec823/num-bigint-0.3.2/src/bigint/power.rs:30
  10: boa::builtins::bigint::operations::<impl boa::builtins::bigint::BigInt>::pow
             at /home/xsh/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.11.0/src/builtins/bigint/operations.rs:11
  11: boa::value::operations::<impl boa::value::Value>::pow
             at /home/xsh/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.11.0/src/value/operations.rs:184
  12: <boa::syntax::ast::node::operator::bin_op::BinOp as boa::exec::Executable>::run
             at /home/xsh/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.11.0/src/syntax/ast/node/operator/bin_op/mod.rs:115
  13: <boa::syntax::ast::node::Node as boa::exec::Executable>::run
             at /home/xsh/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.11.0/src/syntax/ast/node/mod.rs:318
  14: <boa::syntax::ast::node::statement_list::StatementList as boa::exec::Executable>::run
             at /home/xsh/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.11.0/src/syntax/ast/node/statement_list/mod.rs:71
  15: boa::context::Context::eval
             at /home/xsh/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.11.0/src/context.rs:717
```

**Expected behavior**
eval should return error properly instead of panic

**Build environment (please complete the following information):**

- OS: Ubuntu
- Version: 18.04
- Target triple: x86_64-unknown-linux-gnu
- Rustc version: rustc 1.46.0

**Additional context**

**Comment by neeldug** [comment]
Working on this
