### ISSUE TITLE
Sporadic panic when running `boa_tester` on multithreaded mode.

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa#2346]
**Describe the bug**
There is a weird panic that occurs when running the ECMA-262 test suite on multithreaded mode.

**To Reproduce**
Running:
```bash
cargo run --release --bin boa_tester -- run 
```

... sometimes prints:

```bash
thread '<unnamed>' panicked at 'Object already borrowed: BorrowMutError', boa_engine/src/builtins/map/ordered_map.rs:221:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'Object already borrowed: BorrowMutError', boa_engine/src/builtins/map/ordered_map.rs:221:30
stack backtrace:
   0:     0x556ffdce4db7 - std::backtrace_rs::backtrace::libunwind::trace::h9135f25bc195152c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x556ffdce4db7 - std::backtrace_rs::backtrace::trace_unsynchronized::h015ee85be510df51
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x556ffdce4db7 - std::sys_common::backtrace::_print_fmt::h5fad03caa9652a2c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x556ffdce4db7 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b42ca28d244e5c7
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x556ffdc0588c - core::fmt::write::h401e827d053130ed
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17
   5:     0x556ffdcbca94 - std::io::Write::write_fmt::hffec93268f5cde32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/io/mod.rs:1672:15
   6:     0x556ffdce59b6 - std::sys_common::backtrace::_print::h180c4c706ee1d3fb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x556ffdce59b6 - std::sys_common::backtrace::print::hd0c35d18765761c9
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x556ffdce59b6 - std::panicking::default_hook::{{closure}}::h1f023310983bc730
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:295:22
   9:     0x556ffdce6a98 - std::panicking::default_hook::h188fec3334afd5be
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:314:9
  10:     0x556ffdce6a98 - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:698:17
  11:     0x556ffdce6572 - std::panicking::begin_panic_handler::{{closure}}::hfab912107608087a
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:588:13
  12:     0x556ffdce64e6 - std::sys_common::backtrace::__rust_end_short_backtrace::h434b685ce8d9965b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x556ffdce64a2 - rust_begin_unwind
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
  14:     0x556ffdc032e2 - core::panicking::panic_fmt::ha6dc7f2ab2479463
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
  15:     0x556ffdc0a202 - core::result::unwrap_failed::h42ad8e915aa0a906
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
  16:     0x556ffd99a8f9 - <boa_engine::builtins::map::ordered_map::MapLock as gc::trace::Finalize>::finalize::h2711277425f29d61
  17:     0x556ffd99a50a - core::ptr::drop_in_place<boa_engine::builtins::map::ordered_map::MapLock>::h0e4d6a7693c58e32
  18:     0x556ffda99937 - core::ptr::drop_in_place<gc::GcCell<boa_engine::object::Object>>::h37375934530aff44
  19:     0x556ffd983201 - gc::Gc<T>::new::h9195ba2eaf083dc6
  20:     0x556ffdacf801 - boa_engine::builtins::map::map_iterator::MapIterator::create_map_iterator::ha12188c6f889ed64
  21:     0x556ffdaccc11 - boa_engine::builtins::map::Map::entries::h9d4ea743c284745b
  22:     0x556ffd99dde2 - boa_engine::vm::code_block::<impl boa_engine::object::jsobject::JsObject>::call_internal::ha23a35a3d2a92f31
  23:     0x556ffd99dca9 - boa_engine::object::internal_methods::function::function_call{{reify.shim}}::haa66a69e2c36bf6e
  24:     0x556ffd9e9c49 - boa_engine::builtins::iterable::<impl boa_engine::value::JsValue>::get_iterator::ha7a04f627ad044ae
  25:     0x556ffd995277 - boa_engine::builtins::array::Array::from::h8f0c65525abcdd80
  26:     0x556ffd99dde2 - boa_engine::vm::code_block::<impl boa_engine::object::jsobject::JsObject>::call_internal::ha23a35a3d2a92f31
  27:     0x556ffd99dca9 - boa_engine::object::internal_methods::function::function_call{{reify.shim}}::haa66a69e2c36bf6e
  28:     0x556ffd9b9350 - boa_engine::vm::<impl boa_engine::context::Context>::execute_instruction::h4f8bf677a254f69f
  29:     0x556ffd9a8400 - boa_engine::vm::<impl boa_engine::context::Context>::run::hcd74b7d1d1efa1d2
  30:     0x556ffd99ed58 - boa_engine::vm::code_block::<impl boa_engine::object::jsobject::JsObject>::call_internal::ha23a35a3d2a92f31
  31:     0x556ffd99dca9 - boa_engine::object::internal_methods::function::function_call{{reify.shim}}::haa66a69e2c36bf6e
  32:     0x556ffd9b9350 - boa_engine::vm::<impl boa_engine::context::Context>::execute_instruction::h4f8bf677a254f69f
  33:     0x556ffd9a8400 - boa_engine::vm::<impl boa_engine::context::Context>::run::hcd74b7d1d1efa1d2
  34:     0x556ffd99ed58 - boa_engine::vm::code_block::<impl boa_engine::object::jsobject::JsObject>::call_internal::ha23a35a3d2a92f31
  35:     0x556ffd99dca9 - boa_engine::object::internal_methods::function::function_call{{reify.shim}}::haa66a69e2c36bf6e
  36:     0x556ffd9b9350 - boa_engine::vm::<impl boa_engine::context::Context>::execute_instruction::h4f8bf677a254f69f
  37:     0x556ffd9a8400 - boa_engine::vm::<impl boa_engine::context::Context>::run::hcd74b7d1d1efa1d2
  38:     0x556ffd8d9b56 - boa_engine::context::Context::execute::h95aa4cbd939459e2
  39:     0x556ffd8d87c7 - boa_engine::context::Context::eval::h1e3a2e98b127d219
  40:     0x556ffd95a657 - boa_tester::exec::<impl boa_tester::Test>::run_once::h2aefb79fef969244
  41:     0x556ffd959231 - boa_tester::exec::<impl boa_tester::Test>::run::head40dfc87358352
  42:     0x556ffd93ee48 - rayon::iter::plumbing::bridge_producer_consumer::helper::hf0b4082ce43eda3a
  43:     0x556ffd8db711 - rayon_core::join::join_context::{{closure}}::hb447f06cf447820a
  44:     0x556ffd93f167 - rayon::iter::plumbing::bridge_producer_consumer::helper::hf0b4082ce43eda3a
  45:     0x556ffd8db5fe - rayon_core::join::join_context::{{closure}}::hb447f06cf447820a
  46:     0x556ffd93f167 - rayon::iter::plumbing::bridge_producer_consumer::helper::hf0b4082ce43eda3a
  47:     0x556ffd8db711 - rayon_core::join::join_context::{{closure}}::hb447f06cf447820a
  48:     0x556ffd93f167 - rayon::iter::plumbing::bridge_producer_consumer::helper::hf0b4082ce43eda3a
  49:     0x556ffd8db711 - rayon_core::join::join_context::{{closure}}::hb447f06cf447820a
  50:     0x556ffd93f167 - rayon::iter::plumbing::bridge_producer_consumer::helper::hf0b4082ce43eda3a
  51:     0x556ffd8db5fe - rayon_core::join::join_context::{{closure}}::hb447f06cf447820a
  52:     0x556ffd93f167 - rayon::iter::plumbing::bridge_producer_consumer::helper::hf0b4082ce43eda3a
  53:     0x556ffd94aa08 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h7bbb015d78c7a638
  54:     0x556ffdc32c98 - rayon_core::registry::WorkerThread::wait_until_cold::h3aad8f97f3f7dd34
  55:     0x556ffdc35b6e - std::sys_common::backtrace::__rust_begin_short_backtrace::h46fae7379014213b
  56:     0x556ffdc3563f - core::ops::function::FnOnce::call_once{{vtable.shim}}::hd99eb3351daf39b2
  57:     0x556ffdce7ce5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h56d5fc072706762b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/boxed.rs:1935:9
  58:     0x556ffdce7ce5 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h41deef8e33b824bb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/alloc/src/boxed.rs:1935:9
  59:     0x556ffdce7ce5 - std::sys::unix::thread::Thread::new::thread_start::ha6436304a1170bba
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys/unix/thread.rs:108:17
  60:     0x7f3ab71c98fd - <unknown>
  61:     0x7f3ab724ba60 - <unknown>
  62:                0x0 - <unknown>
thread panicked while panicking. aborting.
[1]    333087 IOT instruction (core dumped)
```

**Build environment (please complete the following information):**

- OS: Arch Linux
- Kernel Version: 5.19.13-arch1-1
- Target triple: stable-x86_64-unknown-linux-gnu
- Rustc version: rustc 1.64.0 (a55dd71d5 2022-09-19)

**Additional context**
The stacktrace shows this is is related to the `borrow_mut` call on the `Finalize` method from the `MapLock` type. However, launching the test suit on single-threaded mode never triggers the panic. Possibly related to the global tracking that `Gc` does?

Also, can someone try to replicate the bug?

**Comment by AlvinKuruvilla** [comment]
I tried reproducing this error and got this. This looks closer to the expected behavior
<img width="425" alt="Screenshot 2023-07-17 at 8 45 15 PM" src="https://github.com/boa-dev/boa/assets/46870885/57302437-7a62-48ec-9e07-ebed82bf8f1a">

**Comment by jedel1043** [comment]
Yeah, I think this is already fixed.

**Comment by jedel1043** [comment]
By the way @AlvinKuruvilla, you're getting that error because you need to pull the `test262` submodule if you want to run the tester, like so

```bash
git submodule update --init --recursive
```
