### ISSUE TITLE
panic: iterator [[Done]] was not a boolean

### ISSUE THREAD

**Issue by langston-barrett** [boa-dev/boa#2658]
```javascript
function AddPromise(){}tests=[{body(){}},{body(){}},{body(){async function*agf(a){for await(m of a){yield}}makeIter=function(){return{next(){return{e:this}}}}
iterTwo={[Symbol.asyncIterator]:makeIter}
const genTwo=agf(iterTwo);AddPromise(this.e,genTwo.next())
AddPromise(this.e,genTwo.next())}}]
for(const test of tests){test.body()}
```
```
undefined
thread 'main' panicked at 'iterator [[Done]] was not a boolean', boa_engine/src/vm/opcode/iteration/for_await.rs:24:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:147:5
   3: core::panicking::panic_str
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:131:5
   4: core::option::expect_failed
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/option.rs:1924:5
   5: <boa_engine::vm::opcode::iteration::for_await::ForAwaitOfLoopIterate as boa_engine::vm::opcode::Operation>::execute
   6: boa_engine::vm::<impl boa_engine::context::Context>::execute_instruction
   7: boa_engine::vm::<impl boa_engine::context::Context>::run
   8: <boa_engine::native_function::Closure<F,T> as boa_engine::native_function::TraceableClosure>::call
   9: boa_engine::vm::code_block::<impl boa_engine::object::jsobject::JsObject>::call_internal
  10: boa_engine::object::internal_methods::function::function_call{{reify.shim}}
  11: boa_engine::context::hooks::HostHooks::call_job_callback
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: <boa::Jobs as boa_engine::job::JobQueue>::run_jobs
  14: boa::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by langston-barrett** [comment]
By the way, this bug, #2657, and others can all be found by simply running `boa` on all of the files retrieved by this script:
```sh
#!/usr/bin/env bash

set -e

repos=(
  "v8/v8"
  "mozilla/gecko-dev"
  "svaarala/duktape"
  "Samsung/escargot"
  "jerryscript-project/jerryscript"
  "chakra-core/ChakraCore"
  "boa-dev/boa"
  "cesanta/elk"
  "Starlight-JS/starlight"
  "denoland/deno"
)
mkdir -p js
for repo in "${repos[@]}"; do
  base=$(basename "${repo}")
  if ! [[ -d "${base}" ]]; then
    git clone --jobs 4 --depth 1 "https://github.com/${repo}"
  fi
  for f in $(find "${base}" -type f -name "*.js"); do 
    echo "${f}"
    cp "${f}" js/"${base}-$(sha256sum "${f}" | head -c 5)-$(basename "${f}")"
  done
done
```

**Comment by jedel1043** [comment]
Minimized:

```javascript
async function* agf(a) {
  for await (m of a) {
    yield;
  }
}
iterTwo = {
  [Symbol.asyncIterator]: () => ({
    next() {
      return { e: this };
    }
  })
};

const genTwo = agf(iterTwo);
genTwo.next()
genTwo.next()
```
