### ISSUE TITLE
panic: must have new target

### ISSUE THREAD

**Issue by langston-barrett** [boa-dev/boa#2673]
Found with [tree-splicer](https://github.com/langston-barrett/tree-splicer) on 9a34cb97f16a6fe973f1da3342fe36382047be74, reduced with [treereduce](https://github.com/langston-barrett/treereduce).
```js
const expressions = [
  
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,

  
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  "super()",
  ,
  ,
  ,
  ,
];
function tryRun(s, f = Function) {
  try { f(s)(); } catch {}
}
for (let expr of expressions) {
  tryRun(`void (${expr}?.());`);
}
```
```
thread 'main' panicked at 'must have new target', boa_engine/src/vm/opcode/environment/mod.rs:105:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:147:5
   3: core::panicking::panic_str
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:131:5
   4: core::option::expect_failed
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/option.rs:1924:5
   5: <boa_engine::vm::opcode::environment::SuperCall as boa_engine::vm::opcode::Operation>::execute
   6: boa_engine::vm::<impl boa_engine::context::Context>::execute_instruction
   7: boa_engine::vm::<impl boa_engine::context::Context>::run
   8: boa_engine::vm::code_block::<impl boa_engine::object::jsobject::JsObject>::call_internal
   9: boa_engine::object::internal_methods::function::function_call{{reify.shim}}
  10: <boa_engine::vm::opcode::call::Call as boa_engine::vm::opcode::Operation>::execute
  11: boa_engine::vm::<impl boa_engine::context::Context>::execute_instruction
  12: boa_engine::vm::<impl boa_engine::context::Context>::run
  13: boa_engine::vm::code_block::<impl boa_engine::object::jsobject::JsObject>::call_internal
  14: boa_engine::object::internal_methods::function::function_call{{reify.shim}}
  15: <boa_engine::vm::opcode::call::Call as boa_engine::vm::opcode::Operation>::execute
  16: boa_engine::vm::<impl boa_engine::context::Context>::execute_instruction
  17: boa_engine::vm::<impl boa_engine::context::Context>::run
  18: boa_engine::context::Context::execute
  19: boa_engine::context::Context::eval_script
  20: boa::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by raskad** [comment]
Reduced test:

```js
Function('super()')()
```
