### ISSUE TITLE
panic: Cannot use the undeclared label

### ISSUE THREAD

**Issue by langston-barrett** [boa-dev/boa#2674]
```js
(function(){
  ;;
  ;
  LABEL0: 
  LABEL1: 
  do {
     {
      ;
      continue LABEL0;
    }
    ;
  } while((-3.73961564302253E+18) && __loopvar0 < 3)
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
  ;
})();
```
```
thread 'main' panicked at 'Cannot use the undeclared label', boa_engine/src/bytecompiler/statement/continue.rs:103:23
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_display
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:147:5
   3: core::panicking::panic_str
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:131:5
   4: core::option::expect_failed
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/option.rs:1924:5
   5: boa_engine::bytecompiler::statement::<impl boa_engine::bytecompiler::ByteCompiler>::compile_stmt
   6: boa_engine::bytecompiler::ByteCompiler::compile_statement_list
   7: boa_engine::bytecompiler::statement::<impl boa_engine::bytecompiler::ByteCompiler>::compile_stmt
   8: boa_engine::bytecompiler::ByteCompiler::compile_statement_list
   9: boa_engine::bytecompiler::statement::<impl boa_engine::bytecompiler::ByteCompiler>::compile_stmt
  10: boa_engine::bytecompiler::statement::loop::<impl boa_engine::bytecompiler::ByteCompiler>::compile_do_while_loop
  11: boa_engine::bytecompiler::statement::<impl boa_engine::bytecompiler::ByteCompiler>::compile_stmt
  12: boa_engine::bytecompiler::statement::<impl boa_engine::bytecompiler::ByteCompiler>::compile_stmt
  13: boa_engine::bytecompiler::function::FunctionCompiler::compile
  14: boa_engine::bytecompiler::ByteCompiler::function
  15: boa_engine::bytecompiler::expression::<impl boa_engine::bytecompiler::ByteCompiler>::compile_expr_impl
  16: boa_engine::bytecompiler::ByteCompiler::call
  17: boa_engine::context::Context::compile_script
  18: boa_engine::context::Context::eval_script
  19: boa::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by nekevss** [comment]
Hi! Was this bug found on the v0.16 or on main?

**Comment by langston-barrett** [comment]
9a34cb97f16a6fe973f1da3342fe36382047be74

**Comment by HalidOdat** [comment]
This is fixed! Probably fixed when #3059 which completely removed the `Continue` opcode. So closing this :)
