### ISSUE TITLE
Executing a big JS file will hang forever

### ISSUE THREAD

**Issue by mlafeldt** [boa-dev/boa#3251]
Assuming that #3247 is fixed by #3248, executing [this large JS file](https://github.com/mlafeldt/boa-playground/blob/91754356dcd6ffc80ed59d79b149165d887816f2/broken/ethers-5.7.2.umd.min.js) will never finish:

```
❯ boa --version
boa 0.17.0

❯ boa broken/ethers-5.7.2.umd.min.js
```

Using `boa --trace` shows that the stack is growing and growing.

I could not generate anything useful with `--flowgraph`; there's just too much data.

I sampled the process using Activity Monitor on macOS:

```
Call graph:
    1171 Thread_797395   DispatchQueue_1: com.apple.main-thread  (serial)
      732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      + 732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +   732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +     732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +       732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +         732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +           732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +             732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +               732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                 732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                   732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                     732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                       732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                         732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                           732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                             732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                               732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                 732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                   732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                     732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                       732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                         732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                           732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                             732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                               732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                 732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                   732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                     732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                       732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                         732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                           732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                             732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                               732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                 732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                   732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                     732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                       732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                         732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                           732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                             732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                               732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                 732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                   732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                     732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                       732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                         732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                           732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                             732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                               732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                 732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                   732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                     732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                       732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                         732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                           732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                             732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                               732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                 732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                   732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                     732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                       732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                         732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                           732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                             732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                               732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                                 732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                                   732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                                     732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                                       732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                                         732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                                           732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                                             732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                                               732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                                                 732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
      +                                                                                                                                                   732 boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
 ...
```

```
Total number in stack (recursive counted multiple, when >=5):
        511       boa_engine::vm::_$LT$impl$u20$boa_engine..context..Context$GT$::run::h79d9f4664732829e  (in boa) + 2404  [0x1005fde0c]
        510       boa_engine::object::internal_methods::_$LT$impl$u20$boa_engine..object..jsobject..JsObject$GT$::__call__::hd1f449e86bf3ab6e  (in boa) + 204  [0x1007849e8]
        510       boa_engine::object::operations::_$LT$impl$u20$boa_engine..object..jsobject..JsObject$GT$::create_data_property::h0bdaa8d001bae4b5  (in boa) + 352  [0x10078c72c]
        510       boa_engine::object::property_map::PropertyMap::insert::h99f68180917ecef2  (in boa) + 292  [0x1006f1130]
        510       boa_engine::vm::code_block::_$LT$impl$u20$boa_engine..object..jsobject..JsObject$GT$::call_internal::h13e26f8870893617  (in boa) + 8104  [0x10079c410]
        509       _$LT$boa_engine..vm..opcode..call..Call$u20$as$u20$boa_engine..vm..opcode..Operation$GT$::execute::h79a940d4952ad695  (in boa) + 864  [0x10074593c]
        509       _$LT$boa_engine..vm..opcode..get..name..GetName$u20$as$u20$boa_engine..vm..opcode..Operation$GT$::execute::hc81f78672e4643c3  (in boa) + 248  [0x10053e37c]
        509       _$LT$boa_engine..vm..opcode..get..name..GetNameAndLocator$u20$as$u20$boa_engine..vm..opcode..Operation$GT$::execute::h03dc8507b3b494a8  (in boa) + 248  [0x10053e96c]
        509       boa_engine::builtins::array::Array::push::hb3b5c7f3f8710051  (in boa) + 576  [0x10071ad7c]
        509       boa_engine::environments::runtime::EnvironmentStack::push_function::hdb734c83c74b635b  (in boa) + 536  [0x1007e49dc]
        509       boa_engine::environments::runtime::declarative::PoisonableEnvironment::set::h0ad1549d469f1ec2  (in boa) + 48  [0x1004be580]
        509       boa_engine::object::internal_methods::ordinary_define_own_property::h8a8a904efb8fd709  (in boa) + 440  [0x1004c1264]
        509       boa_engine::object::internal_methods::ordinary_get::h23e07e71cdf27fdd  (in boa) + 224  [0x1004c1878]
        509       boa_engine::object::internal_methods::ordinary_set::hebbd84b4fcdefe9c  (in boa) + 1612  [0x1004c2478]
        509       boa_engine::object::internal_methods::ordinary_set::hebbd84b4fcdefe9c  (in boa) + 408  [0x1004c1fc4]
        509       boa_engine::object::internal_methods::ordinary_set::hebbd84b4fcdefe9c  (in boa) + 488  [0x1004c2014]
        509       boa_engine::object::internal_methods::validate_and_apply_property_descriptor::h43871cd7f877bcea  (in boa) + 1868  [0x1004c3580]
        509       boa_engine::object::property_map::PropertyMap::get::h6f9bdf20b2b297b7  (in boa) + 492  [0x1006f07c8]
        509       boa_gc::Allocator::manage_state::ha0a5c6018988a4cd  (in boa) + 36  [0x10098c1b0]
        509       boa_gc::internals::gc_box::GcBox$LT$T$GT$::mark_and_trace::h0ee140a45d3be993  (in boa) + 312  [0x100568be8]
        509       boa_gc::internals::gc_box::GcBox$LT$T$GT$::mark_and_trace::h0ee140a45d3be993  (in boa) + 80  [0x100568b00]
        509       boa_gc::pointers::gc::Gc$LT$T$GT$::new::h09cd3fc0508e26e1  (in boa) + 76  [0x1005227d4]
        509       boa_gc::pointers::gc::Gc$LT$T$GT$::new::h895addc214040540  (in boa) + 88  [0x1005235ac]
        509       core::ptr::drop_in_place$LT$boa_engine..environments..runtime..EnvironmentStack$GT$::h60d4eeda9b0bafd4  (in boa) + 104  [0x1007502c4]

Sort by top of stack, same collapsed (when >= 5):
        _$LT$boa_engine..object..Object$u20$as$u20$boa_gc..trace..Trace$GT$::root::haaddb21b6061d447  (in boa)        564
        _$LT$boa_engine..object..Object$u20$as$u20$boa_gc..trace..Trace$GT$::unroot::h9593d1ae04ce07eb  (in boa)        546
        boa_engine::vm::code_block::_$LT$impl$u20$boa_engine..object..jsobject..JsObject$GT$::call_internal::h13e26f8870893617  (in boa)        10
        core::hash::BuildHasher::hash_one::hd74516b47ffb2119  (in boa)        10
```

[Full sample file](https://github.com/boa-dev/boa/files/12498133/Sample.of.boa.txt)

**Comment by mlafeldt** [comment]
Patched `ordinary_define_own_property` to get more info:

```diff
--- boa_engine/src/object/internal_methods/mod.rs
+++ boa_engine/src/object/internal_methods/mod.rs
@@ -457,6 +457,7 @@ pub(crate) fn ordinary_define_own_property(
     desc: PropertyDescriptor,
     context: &mut Context<'_>,
 ) -> JsResult<bool> {
+    println!("{obj:?} {key:?}");
     let _timer = Profiler::global().start_event("Object::ordinary_define_own_property", "object");
     // 1. Let current be ? O.[[GetOwnProperty]](P).
     let current = obj.__get_own_property__(key, context)?;

```

Looks like it's working tirelessly on some array without finishing:

```
(Ordinary) 0x14D70F5F0 String("globalThis")
(Ordinary) 0x14D70F5F0 String("Infinity")
(Ordinary) 0x14D70F5F0 String("NaN")
(Ordinary) 0x14D70F5F0 String("undefined")
(Ordinary) 0x14D70F5F0 String("Function")
(Ordinary) 0x14D70F5F0 String("Object")
(Ordinary) 0x14D70F5F0 String("Math")
(Ordinary) 0x14D70F5F0 String("JSON")
(Ordinary) 0x14D70F5F0 String("Array")
(Ordinary) 0x14D70F5F0 String("Proxy")
(Ordinary) 0x14D70F5F0 String("ArrayBuffer")
(Ordinary) 0x14D70F5F0 String("BigInt")
(Ordinary) 0x14D70F5F0 String("Boolean")
(Ordinary) 0x14D70F5F0 String("Date")
(Ordinary) 0x14D70F5F0 String("DataView")
(Ordinary) 0x14D70F5F0 String("Map")
(Ordinary) 0x14D70F5F0 String("isFinite")
(Ordinary) 0x14D70F5F0 String("isNaN")
(Ordinary) 0x14D70F5F0 String("parseInt")
(Ordinary) 0x14D70F5F0 String("parseFloat")
(Ordinary) 0x14D70F5F0 String("Number")
(Ordinary) 0x14D70F5F0 String("eval")
(Ordinary) 0x14D70F5F0 String("Set")
(Ordinary) 0x14D70F5F0 String("String")
(Ordinary) 0x14D70F5F0 String("RegExp")
(Ordinary) 0x14D70F5F0 String("TypedArray")
(Ordinary) 0x14D70F5F0 String("Int8Array")
(Ordinary) 0x14D70F5F0 String("Uint8Array")
(Ordinary) 0x14D70F5F0 String("Uint8ClampedArray")
(Ordinary) 0x14D70F5F0 String("Int16Array")
(Ordinary) 0x14D70F5F0 String("Uint16Array")
(Ordinary) 0x14D70F5F0 String("Int32Array")
(Ordinary) 0x14D70F5F0 String("Uint32Array")
(Ordinary) 0x14D70F5F0 String("BigInt64Array")
(Ordinary) 0x14D70F5F0 String("BigUint64Array")
(Ordinary) 0x14D70F5F0 String("Float32Array")
(Ordinary) 0x14D70F5F0 String("Float64Array")
(Ordinary) 0x14D70F5F0 String("Symbol")
(Ordinary) 0x14D70F5F0 String("Error")
(Ordinary) 0x14D70F5F0 String("RangeError")
(Ordinary) 0x14D70F5F0 String("ReferenceError")
(Ordinary) 0x14D70F5F0 String("TypeError")
(Ordinary) 0x14D70F5F0 String("SyntaxError")
(Ordinary) 0x14D70F5F0 String("EvalError")
(Ordinary) 0x14D70F5F0 String("URIError")
(Ordinary) 0x14D70F5F0 String("AggregateError")
(Ordinary) 0x14D70F5F0 String("Reflect")
(Ordinary) 0x14D70F5F0 String("Promise")
(Ordinary) 0x14D70F5F0 String("encodeURI")
(Ordinary) 0x14D70F5F0 String("encodeURIComponent")
(Ordinary) 0x14D70F5F0 String("decodeURI")
(Ordinary) 0x14D70F5F0 String("decodeURIComponent")
(Ordinary) 0x14D70F5F0 String("WeakRef")
(Ordinary) 0x14D70F5F0 String("WeakMap")
(Ordinary) 0x14D70F5F0 String("WeakSet")
(Ordinary) 0x14D70F5F0 String("escape")
(Ordinary) 0x14D70F5F0 String("unescape")
(Ordinary) 0x14D70F5F0 String("atob")
(Ordinary) 0x14D70F5F0 String("atob")
(Ordinary) 0x14D70F5F0 String("btoa")
(Ordinary) 0x14D70F5F0 String("btoa")
(Ordinary) 0x13D7BB7D0 String("path")
(Ordinary) 0x13D7BB7D0 String("exports")
(Ordinary) 0x13D7BB7D0 String("require")
(Ordinary) 0x13D7BB7D0 String("exports")
(Function) "BN" 0x13D7A9740 String("BN")
(Function) "BN" 0x13D7A9740 String("wordSize")
(Error) 0x13D7B19A0 String("message")
(Function) "BN" 0x13D7A9740 String("isBN")
(Function) "BN" 0x13D7A9740 String("max")
(Function) "BN" 0x13D7A9740 String("min")
(Ordinary) 0x13D7A95B0 String("_init")
(Ordinary) 0x13D7A95B0 String("_initNumber")
(Ordinary) 0x13D7A95B0 String("_initArray")
(Ordinary) 0x13D7A95B0 String("_parseHex")
(Ordinary) 0x13D7A95B0 String("_parseBase")
(Ordinary) 0x13D7A95B0 String("copy")
(Ordinary) 0x13D7A95B0 String("_move")
(Ordinary) 0x13D7A95B0 String("clone")
(Ordinary) 0x13D7A95B0 String("_expand")
(Ordinary) 0x13D7A95B0 String("_strip")
(Ordinary) 0x13D7A95B0 String("_normSign")
(Ordinary) 0x13D7A95B0 Symbol(JsSymbol { hash: 128, description: Some("nodejs.util.inspect.custom") })
(Array) 0x13D7B5A00 Index(0)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(1)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(2)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(3)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(4)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(5)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(6)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(7)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(8)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(9)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(10)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(11)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(12)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(13)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(14)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(15)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(16)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(17)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(18)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(19)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(20)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(21)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(22)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(23)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(24)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5A00 Index(25)
(Array) 0x13D7B5A00 String("length")
(Array) 0x13D7B5DA0 Index(0)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(1)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(2)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(3)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(4)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(5)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(6)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(7)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(8)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(9)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(10)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(11)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(12)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(13)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(14)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(15)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(16)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(17)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(18)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(19)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(20)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(21)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(22)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(23)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(24)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(25)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(26)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(27)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(28)
(Array) 0x13D7B5DA0 String("length")
(Array) 0x13D7B5DA0 Index(29)
(Array) 0x13D7B5DA0 String("length")
...
(Array) 0x13D9E3B90 Index(102321)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102322)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102323)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102324)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102325)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102326)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102327)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102328)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102329)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102330)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102331)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102332)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102333)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102334)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102335)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102336)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102337)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102338)
(Array) 0x13D9E3B90 String("length")
(Array) 0x13D9E3B90 Index(102339)
(Array) 0x13D9E3B90 String("length")
...
(Array) 0x10A709CD0 Index(237671)
(Array) 0x10A709CD0 String("length")
(Array) 0x10A709CD0 Index(237672)
(Array) 0x10A709CD0 String("length")
(Array) 0x10A709CD0 Index(237673)
(Array) 0x10A709CD0 String("length")
(Array) 0x10A709CD0 Index(237674)
(Array) 0x10A709CD0 String("length")
(Array) 0x10A709CD0 Index(237675)
(Array) 0x10A709CD0 String("length")
(Array) 0x10A709CD0 Index(237676)
(Array) 0x10A709CD0 String("length")
(Array) 0x10A709CD0 Index(237677)
...
```

**Comment by jedel1043** [comment]
This is just a bug in the original script. Running it using Node returns:
```shell
#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 169220804 (see crbug.com/1201626)
#
#
#
#FailureMessage Object: 0x7ffc5d2d4e20
----- Native stack trace -----

 1: 0xd38851  [node]
 2: 0x216e041 V8_Fatal(char const*, ...) [node]
 3: 0x10beb18  [node]
 4: 0x129dccf  [node]
 5: 0x129de6a  [node]
 6: 0x15183a6 v8::internal::Runtime_GrowArrayElements(int, unsigned long*, v8::internal::Isolate*) [node]
 7: 0x7736f7ed9ef6 
[1]    39685 trace trap (core dumped)  node ./experim/main2.js
```
Which is always caused by the equivalent of:
```
let a = []
while(true) {
  a.push(0)
}
```

**Comment by mlafeldt** [comment]
I get this error with both Deno and Node.

```
RangeError: Invalid array length
    at Array.push (<anonymous>)
    at read_zero_terminated_array (/private/tmp/ethers-5.7.2.umd.min.js:4:193424)
    at read_linear_table (/private/tmp/ethers-5.7.2.umd.min.js:4:193761)
    at read_mapped_map (/private/tmp/ethers-5.7.2.umd.min.js:4:193154)
    at /private/tmp/ethers-5.7.2.umd.min.js:4:210172
    at createCommonjsModule (/private/tmp/ethers-5.7.2.umd.min.js:4:767)
    at /private/tmp/ethers-5.7.2.umd.min.js:4:209822
    at /private/tmp/ethers-5.7.2.umd.min.js:4:97
    at Object.<anonymous> (/private/tmp/ethers-5.7.2.umd.min.js:4:252)
    at Module._compile (node:internal/modules/cjs/loader:1740:14)

Node.js v23.5.0
```

Getting an error is fine. The bug report was about Boa hanging forever, which might have changed in the meantime.

**Comment by jedel1043** [comment]
Boa hangs because, funnily enough, it is slow, so the script just takes ages to reach its memory limits.
