### ISSUE TITLE
Panic on invalid input to boa::parse

### ISSUE THREAD

**Issue by MinghuaWang** [boa-dev/boa#3631]
**Describe the bug**
Panic could be triggered when passing  boa::parse with invalid input. Panic info is shown below:
```
thread 'main' panicked at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/primary/object_initializer/mod.rs:272:51:
current token disappeared
```

**To Reproduce**
It can be reproduced with the following program: 

```Rust
fn main() {
    let data =[0x09, 0x76, 0x61, 0x72, 0x31, 0x5b, 0x7b, 0x20, 0x67, 0x65, 0x74, 0x20, 0x75, 0x68, 0x28, 0x20];
    if let Ok(s) = std::str::from_utf8(&data) {
        let _ = boa::parse(s, true);
    }
}
```

**Expected behavior**
Not panic. It could be an error reported to the users.

**Build environment (please complete the following information):**

- OS: Ubuntu 20.04, 64 bit
- Version: 0.13.1
- Target triple: x86_64-unknown-linux-gnu
- Rustc version: rustc 1.73.0-nightly (076887268 2023-08-17)

**Additional context**
Full stacktrace:
```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07688726805d5db0a4bca445a6651d09708041ea/library/std/src/panicking.rs:617:5
   1: core::panicking::panic_fmt
             at /rustc/07688726805d5db0a4bca445a6651d09708041ea/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/07688726805d5db0a4bca445a6651d09708041ea/library/core/src/panicking.rs:150:5
   3: core::panicking::panic_str
             at /rustc/07688726805d5db0a4bca445a6651d09708041ea/library/core/src/panicking.rs:134:5
   4: core::option::expect_failed
             at /rustc/07688726805d5db0a4bca445a6651d09708041ea/library/core/src/option.rs:1988:5
   5: core::option::Option<T>::expect
             at /rustc/07688726805d5db0a4bca445a6651d09708041ea/library/core/src/option.rs:898:21
   6: <boa::syntax::parser::expression::primary::object_initializer::MethodDefinition as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/primary/object_initializer/mod.rs:272:35
   7: <boa::syntax::parser::expression::primary::object_initializer::PropertyDefinition as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/primary/object_initializer/mod.rs:208:20
   8: <boa::syntax::parser::expression::primary::object_initializer::ObjectLiteral as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/primary/object_initializer/mod.rs:74:23
   9: <boa::syntax::parser::expression::primary::PrimaryExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/primary/mod.rs:103:20
  10: <boa::syntax::parser::expression::left_hand_side::member::MemberExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/left_hand_side/member.rs:82:13
  11: <boa::syntax::parser::expression::left_hand_side::LeftHandSideExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/left_hand_side/mod.rs:67:19
  12: <boa::syntax::parser::expression::update::UpdateExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/update.rs:79:19
  13: <boa::syntax::parser::expression::assignment::exponentiation::ExponentiationExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/assignment/exponentiation.rs:91:19
  14: <boa::syntax::parser::expression::MultiplicativeExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:82:27
  15: <boa::syntax::parser::expression::AdditiveExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:82:27
  16: <boa::syntax::parser::expression::ShiftExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:82:27
  17: <boa::syntax::parser::expression::RelationalExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:489:23
  18: <boa::syntax::parser::expression::EqualityExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:82:27
  19: <boa::syntax::parser::expression::BitwiseANDExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:82:27
  20: <boa::syntax::parser::expression::BitwiseXORExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:82:27
  21: <boa::syntax::parser::expression::BitwiseORExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:82:27
  22: <boa::syntax::parser::expression::ShortCircuitExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:218:13
  23: <boa::syntax::parser::expression::assignment::conditional::ConditionalExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/assignment/conditional.rs:68:19
  24: <boa::syntax::parser::expression::assignment::AssignmentExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/assignment/mod.rs:175:23
  25: <boa::syntax::parser::expression::Expression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:82:27
  26: <boa::syntax::parser::expression::left_hand_side::member::MemberExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/left_hand_side/member.rs:112:25
  27: <boa::syntax::parser::expression::left_hand_side::LeftHandSideExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/left_hand_side/mod.rs:67:19
  28: <boa::syntax::parser::expression::update::UpdateExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/update.rs:79:19
  29: <boa::syntax::parser::expression::assignment::exponentiation::ExponentiationExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/assignment/exponentiation.rs:91:19
  30: <boa::syntax::parser::expression::MultiplicativeExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:82:27
  31: <boa::syntax::parser::expression::AdditiveExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:82:27
  32: <boa::syntax::parser::expression::ShiftExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:82:27
  33: <boa::syntax::parser::expression::RelationalExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:489:23
  34: <boa::syntax::parser::expression::EqualityExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:82:27
  35: <boa::syntax::parser::expression::BitwiseANDExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:82:27
  36: <boa::syntax::parser::expression::BitwiseXORExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:82:27
  37: <boa::syntax::parser::expression::BitwiseORExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:82:27
  38: <boa::syntax::parser::expression::ShortCircuitExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:218:13
  39: <boa::syntax::parser::expression::assignment::conditional::ConditionalExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/assignment/conditional.rs:68:19
  40: <boa::syntax::parser::expression::assignment::AssignmentExpression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/assignment/mod.rs:175:23
  41: <boa::syntax::parser::expression::Expression as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/expression/mod.rs:82:27
  42: <boa::syntax::parser::statement::expression::ExpressionStatement as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/statement/expression/mod.rs:46:20
  43: <boa::syntax::parser::statement::Statement as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/statement/mod.rs:218:17
  44: <boa::syntax::parser::statement::StatementListItem as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/statement/mod.rs:467:17
  45: <boa::syntax::parser::statement::StatementList as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/statement/mod.rs:292:24
  46: <boa::syntax::parser::ScriptBody as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/mod.rs:160:9
  47: <boa::syntax::parser::Script as boa::syntax::parser::TokenParser<R>>::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/mod.rs:135:42
  48: boa::syntax::parser::Parser<R>::parse_all
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/syntax/parser/mod.rs:105:9
  49: boa::parse
             at /home/test/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/Boa-0.13.1/src/lib.rs:96:5
  50: boa_test::main
             at ./src/main.rs:17:17
  51: core::ops::function::FnOnce::call_once
             at /rustc/07688726805d5db0a4bca445a6651d09708041ea/library/core/src/ops/function.rs:250:5
```

**Comment by jedel1043** [comment]
Just a heads up: The [`Boa`](https://crates.io/crates/Boa) crate was deprecated and replaced by the [`boa_engine`](https://crates.io/crates/boa_engine) crate.

Since I tested that the panic is not present on neither 0.17.3 nor main, closing this.
