### ISSUE TITLE
panic at 'RangeError: Maximum BigInt size exceeded'

### ISSUE THREAD

**Issue by alexanderkjall** [boa-dev/boa#883]
**Describe the bug**
I expected something like:
`Uncaught RangeError: BigInt is too large to allocate`

Instead I got a panic

**To Reproduce**
Reproduce with:

```
fn main() {
    let mut context = boa::Context::new();
    let _ = context.eval("9722n>>-155555555555558n>>-1555");
}
```

**Expected behavior**
Firefox gives me:
`Uncaught RangeError: BigInt is too large to allocate`

**Build environment (please complete the following information):**

- OS: Ubuntu 20.04
- Version: 0.10.0
- Target triple: [e.g. x86_64-unknown-linux-gnu]
- Rustc version: rustc 1.49.0-nightly (dd7fc54eb 2020-10-15)

**Additional context**
backtrace:
```
thread 'main' panicked at 'RangeError: Maximum BigInt size exceeded', /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.10.0/src/builtins/bigint/operations.rs:75:9
stack backtrace:
   0: std::panicking::begin_panic
             at /home/capitol/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:505:12
   1: boa::builtins::bigint::operations::<impl core::ops::bit::Shr for boa::builtins::bigint::BigInt>::shr
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.10.0/src/builtins/bigint/operations.rs:75:9
   2: boa::value::operations::<impl boa::value::Value>::shr
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.10.0/src/value/operations.rs:329:30
   3: boa::exec::operator::<impl boa::exec::Executable for boa::syntax::ast::node::operator::BinOp>::run
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.10.0/src/exec/operator/mod.rs:74:35
   4: <boa::syntax::ast::node::Node as boa::exec::Executable>::run
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.10.0/src/exec/mod.rs:107:36
   5: boa::exec::operator::<impl boa::exec::Executable for boa::syntax::ast::node::operator::BinOp>::run
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.10.0/src/exec/operator/mod.rs:67:25
   6: <boa::syntax::ast::node::Node as boa::exec::Executable>::run
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.10.0/src/exec/mod.rs:107:36
   7: boa::exec::statement_list::<impl boa::exec::Executable for boa::syntax::ast::node::statement_list::StatementList>::run
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.10.0/src/exec/statement_list.rs:17:23
   8: boa::context::Context::eval
             at /home/capitol/.cargo/registry/src/github.com-1ecc6299db9ec823/Boa-0.10.0/src/context.rs:494:25
   9: boa_reproduce::main
             at ./src/main.rs:3:13
  10: core::ops::function::FnOnce::call_once
             at /home/capitol/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
```

**Comment by georgeroman** [comment]
A similar panic happens if you raise a BigInt to a negative exponent:
```
>> 10n ** (-9n)
thread 'main' panicked at 'RangeError: "BigInt negative exponent"', boa/src/builtins/bigint/operations.rs:16:22
```

**Comment by Razican** [comment]
Now that #884 got merged, do these still happen?

**Comment by georgeroman** [comment]
The panics don't happen anymore, but `1000n << 10000000n` taking forever is still on.

**Comment by Razican** [comment]
I have opened #1053 to track the `BigInt` taking forever , so I'm closing this, as the panic has been fixed.
